name = "Legacy of Adventure"
author = "Xylophone34"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a157245543b33c948a8d88774c7589d2bd3fb71f67159e3e93f9df7c9a3050e"

[versions]
forge = "47.4.17"
minecraft = "1.20.1"
