name = "Legacy of Adventure"
author = "Xylophone34"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf8906a5c24fcc271550f81dafa348b7ce33ec56f79ac6afa44fcca884bbf44c"

[versions]
forge = "47.4.17"
minecraft = "1.20.1"
