name = "Legacy of Adventure"
author = "Xylophone34"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "392b68ee71726cfc27634f017d8e68c2ac4456ebbbe4809134fb90d6ed629534"

[versions]
forge = "47.4.17"
minecraft = "1.20.1"
